# Generated by Django 3.1.1 on 2020-09-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensorreading_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='temp',
            field=models.FloatField(),
        ),
    ]
